# Generated by Django 3.2.5 on 2021-10-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='payment_id',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='donate',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
