# Generated by Django 3.2.5 on 2021-10-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razor', '0002_auto_20211022_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='order_id',
            new_name='payment_id',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='razorpay_payment_id',
        ),
    ]
